#Config.yml for BlockFilter by Fitta
MESSAGES:
  NO_PERMISSION: '&cNah fam, No perms'
  COBBLE:
    ENABLED_PICKUP: '&aEnabled cobblestone pickups'
    DISABLED_PICKUP: '&cDisabled cobblestone pickups'